# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_auto_20170418_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='statement',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
    ]
