# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0005_question_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(choices=[('Option1', '1'), ('Option2', '2'), ('Option3', '3'), ('Option4', '4')]),
        ),
    ]
