# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0011_auto_20170420_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='sumeet.dang101@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='last', max_length=100),
            preserve_default=False,
        ),
    ]
