# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0012_auto_20170420_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('num_questions', models.SmallIntegerField()),
            ],
        ),
    ]
