# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0015_auto_20170422_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='testschedule',
            name='time_limit',
            field=models.SmallIntegerField(default=6),
            preserve_default=False,
        ),
    ]
