# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0016_testschedule_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField()),
                ('score', models.SmallIntegerField()),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.Candidate')),
            ],
        ),
    ]
